---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: https://vault-active.vault.svc:8200
      path: cledyu
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: cledyu-eso
          serviceAccountRef:
            name: eso-vault-auth
            namespace: external-secrets
      caProvider:
        type: Secret
        name: vault-tls
        namespace: vault
        key: ca.crt
