---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: vault
  namespace: vault
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  serverName: vault-active.vault.svc
  rootCAsSecrets:
    - vault-tls
