apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-monitoring
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 69.3.2
      helm:
        releaseName: kps
        valueFiles:
          - $values/gitops/apps/kube-prometheus-stack/values.yaml
    - repoURL: https://github.com/requset700k/Cledyu.git
      targetRevision: feat/monitoring-foundation
      ref: values
    - repoURL: https://github.com/requset700k/Cledyu.git
      targetRevision: feat/monitoring-foundation
      path: infra/kubernetes/monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
