---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-oidc
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: grafana-oidc
    creationPolicy: Owner
  data:
    - secretKey: client-secret
      remoteRef:
        key: cledyu/oidc/grafana
        property: client_secret
