---
keycloak_foundation_namespace: keycloak
keycloak_foundation_name: cledyu-keycloak
keycloak_foundation_kubeconfig: /home/ubuntu/.kube/config
keycloak_foundation_manifest_path: /home/ubuntu/keycloak-foundation.yaml
keycloak_foundation_certificate_manifest_path: /home/ubuntu/keycloak-certificate.yaml
keycloak_foundation_ingress_manifest_path: /home/ubuntu/keycloak-ingress.yaml
keycloak_foundation_service_account_manifest_path: /home/ubuntu/keycloak-serviceaccount.yaml

keycloak_foundation_api_group: k8s.keycloak.org
keycloak_foundation_cr_version_preferred: v2
keycloak_foundation_cr_version_fallbacks:
  - v2beta1
  - v2alpha1
keycloak_foundation_cr_version_override: ""

keycloak_foundation_instances: 1
keycloak_foundation_db_service_name: keycloak-db-postgresql
keycloak_foundation_db_secret_name: keycloak-db-credentials
keycloak_foundation_service_name: "{{ keycloak_foundation_name }}-service"
keycloak_foundation_service_account_name: cledyu-keycloak
keycloak_foundation_hostname: keycloak.cledyu.local

keycloak_foundation_tls_certificate_name: keycloak-tls
keycloak_foundation_tls_secret_name: keycloak-tls
keycloak_foundation_ingress_name: keycloak
