---
collections:
  - name: ansible.posix
    version: ">=1.5.4"
  - name: community.general
    version: ">=8.0.0"
  - name: kubernetes.core
    version: ">=3.2.0"
  - name: ansible.windows
    version: ">=1.14.0,<2.0.0"
