---
- name: reload-sysctl
  ansible.builtin.command: sysctl --system
  listen: reload-sysctl

- name: restart-containerd
  ansible.builtin.systemd:
    name: containerd
    state: restarted
    enabled: true
  listen: restart-containerd
