name: build-api

on:
  pull_request:
    branches: [main]
    paths:
      - apps/api/**
      - .github/workflows/build-image.yml
      - .github/workflows/build-api.yml
  push:
    branches: [main]
    paths:
      - apps/api/**
      - .github/workflows/build-image.yml
      - .github/workflows/build-api.yml
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  image:
    uses: ./.github/workflows/build-image.yml
    with:
      context: apps/api
      image-name: api
      trivyignores: apps/api/.trivyignore
    secrets: inherit
